# conda create --name in2 --clone ineye
# conda env create -n ineye --file environment.yml --force
# conda env update -n ineye --file environment.yml --prune
# conda env remove -n ineye
# Python 3.7 works for Ubuntu 18+ and Python 3.8 for MacOS environment
name: ineye
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyterlab
  - tqdm
  - pandas
  - pillow
  - matplotlib
  - scikit-learn
  - scikit-image
  - scipy
  - pip:
    - PyQt6
    - opencv-python==4.8.1.78
    - opencv-contrib-python==4.8.1.78
    - opencv-python-headless==4.8.1.78
    - ultralytics # to use YOLOv8
    - deep-sort-realtime
    - torch 
    - torchvision 
    - torchaudio